language: python
sudo: required
cache:
  directories:
    - ~/.cache/pip

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
    - TESTDATA_DIR=$HOME/testdata

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libgdal-dev
      - libudunits2-dev
      - python-gdal
      - python3-gdal
      - libspatialite-dev
      - swig2.0
      - libproj-dev
      - gdal-bin

python:
  - '3.4'

virtualenv:
  system_site_packages: true

install:
  - pip install -r requirements.txt
  - pip install coveralls coverage
  - python setup.py install

script:
  - coverage run --source spatialist/ -m pytest

after_success:
- coveralls
